export const OPEN_FILE = "OPEN_FILE";
export const SET_EDITOR = "SET_EDITOR";
export const CHANGE_THEME = "CHANGE_THEME";
export const CLOSE_FILE = "CLOSE_FILE";
export const DECREMENT_FONT_SIZE = "DECREMENT_FONT_SIZE";
export const INCREMENT_FONT_SIZE = "INCREMENT_FONT_SIZE";
