export const OPEN_FILE = "OPEN_FILE";
export const SET_EDITOR = "SET_EDITOR";
export const CHANGE_THEME = "CHANGE_THEME";
export const CLOSE_FILE = "CLOSE_FILE";
export const CHANGE_FONT_SIZE = "CHANGE_FONT_SIZE";
export const CHANGE_NUMERAL_SYSTEM = "CHANGE_NUMERAL_SYSTEM";
